version: '3.8'

services:
  node-back-end-uat:
    build:
      context: ../../
      dockerfile: docker/uat/Dockerfile
    image: node-back-end-uat
    ports:
      - '9091:9081'
    env_file:
      - ../../.env.uat
    networks:
      - test_origin_default

networks:
  test_origin_default:
    external: true
