version: '3.8'

services:
  node-back-end-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: node-back-end-production
    ports:
      - '9090:9082'
    env_file:
      - ../../.env.production
    networks:
      - test_origin_default

networks:
  test_origin_default:
    external: true
